### ISSUE TITLE
Error hit by ebpf-docs repo

### ISSUE THREAD

**Issue by dthaler** [dthaler/rst2rfcxml#130]
https://github.com/ietf-wg-bpf/ebpf-docs/actions/runs/6784438622/job/18440736964 :
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/xml2rfc", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/run.py", line 746, in main
    writer.write(filename)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 279, in write
    html_tree = self.html_tree()
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 257, in html_tree
    html_tree = self.render(None, self.root)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 334, in render
    res = func(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 677, in render_rfc
    self.render(body, c)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 334, in render
    res = func(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 348, in skip_renderer
    self.render(h, c)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 334, in render
    res = func(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 2398, in render_section
    self.render(section, c)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 334, in render
    res = func(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 2677, in render_ul
    self.render(ul, c)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 334, in render
    res = func(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 1800, in render_li
    li = self.render_li_ul(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 1794, in render_li_ul
    self.render(li, c)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 334, in render
    res = func(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 2528, in render_t
    self.render(p, c)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 334, in render
    res = func(h, x)
  File "/home/runner/.local/lib/python3.8/site-packages/xml2rfc/writers/html.py", line 2[88](https://github.com/ietf-wg-bpf/ebpf-docs/pull/62/checks#step:7:89)8, in render_xref
    label = 'Section' if section[0].isdigit() else 'Appendix' if re.search(r'^[A-Z](\.|$)', section) else 'Part'
IndexError: string index out of range
```

**Comment by dthaler** [comment]
Possibly a bug in xml2rfc?  There may be a problem in the XML but still, xml2rfc should generate a better error message if so.
